[package]
name = "hinku"
version = "0.1.0"
authors = ["Mitja Karhusaari <mitja@karhusaari.me>"]
edition = "2018"

[feature]
logos = ["logos"]

[dependencies]
logos = { version = "0.11.4", optional = true }
